"""initial_schema

Revision ID: 45f0d0797734
Revises: 
Create Date: 2026-03-06 18:19:09.761890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f0d0797734'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the full Lumnos schema (49 tables + 28 indexes).

    This baseline migration applies the complete PostgreSQL schema
    generated by app/core/migrate_postgres.py.
    """
    from app.core.migrate_postgres import POSTGRES_SCHEMA
    op.execute(POSTGRES_SCHEMA)


def downgrade() -> None:
    """Drop all Lumnos tables (reverse of initial_schema)."""
    tables = [
        "chat_feedbacks_v2", "prompt_vorschlaege", "knowledge_updates",
        "lehrplan_themen", "quiz_confidence", "ws_tickets", "schulbuch_scans",
        "marketplace_purchases", "parent_link_requests", "battle_pass",
        "noten_prognose", "question_history", "xp_log", "flashcards",
        "notifications", "marketplace_items", "ki_relationship",
        "seasonal_events", "parent_links", "daily_quests", "spaced_repetition",
        "challenge_progress", "challenges_db", "shop_purchases",
        "pomodoro_sessions", "push_subscriptions", "school_licenses",
        "multiplayer_rooms", "chat_feedback", "iq_results", "iq_tests",
        "admin_logs", "tournament_entries", "tournaments",
        "coupon_redemptions", "coupons", "research_results", "group_chats",
        "gamification", "wochen_coach_plans", "abitur_simulations",
        "user_memories", "activity_log", "quiz_answers", "learning_resources",
        "quiz_results", "chat_sessions", "learning_profiles", "users",
    ]
    for table in tables:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
