#!/usr/bin/env python3
"""PR #48: Supabase PostgreSQL Setup Script.

Converts all SQLite table definitions to PostgreSQL-compatible SQL
and executes them against a Supabase PostgreSQL database.

Usage:
    DATABASE_URL="postgresql://user:pass@host:5432/dbname" python scripts/supabase_setup.py

Conversions:
    - INTEGER PRIMARY KEY AUTOINCREMENT → SERIAL PRIMARY KEY
    - TEXT DEFAULT (datetime('now')) → TIMESTAMP DEFAULT NOW()
    - TEXT DEFAULT '' → VARCHAR DEFAULT ''
    - INTEGER DEFAULT 0 → INTEGER DEFAULT 0 (unchanged)
    - REAL DEFAULT 0.0 → DOUBLE PRECISION DEFAULT 0.0
    - CREATE INDEX IF NOT EXISTS → CREATE INDEX IF NOT EXISTS (unchanged)
"""
import os
import sys
import logging

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# All 50 tables from database.py, converted to PostgreSQL syntax
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

POSTGRES_TABLES = """
-- ══════════════════════════════════════════════════
-- Lumnos EduAI Companion — PostgreSQL Schema
-- Generated by scripts/supabase_setup.py (PR #48)
-- ══════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    username VARCHAR UNIQUE NOT NULL,
    hashed_password VARCHAR NOT NULL,
    full_name VARCHAR DEFAULT '',
    school_grade VARCHAR DEFAULT '10',
    school_type VARCHAR DEFAULT 'Gymnasium',
    preferred_language VARCHAR DEFAULT 'de',
    is_pro INTEGER DEFAULT 0,
    subscription_tier VARCHAR DEFAULT 'free',
    ki_personality_id INTEGER DEFAULT 1,
    ki_personality_name VARCHAR DEFAULT 'Freundlich',
    stripe_customer_id VARCHAR DEFAULT '',
    pro_since VARCHAR DEFAULT '',
    clerk_user_id VARCHAR DEFAULT '',
    avatar_url VARCHAR DEFAULT '',
    auth_provider VARCHAR DEFAULT 'local',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    -- Migration columns
    pro_expires_at VARCHAR DEFAULT '',
    billing_period VARCHAR DEFAULT 'monthly',
    is_admin INTEGER DEFAULT 0,
    streak_days INTEGER DEFAULT 0,
    longest_streak INTEGER DEFAULT 0,
    last_active VARCHAR DEFAULT '',
    bundesland VARCHAR DEFAULT '',
    klasse INTEGER DEFAULT 10,
    schultyp_detail VARCHAR DEFAULT 'Gymnasium',
    favoriten_faecher VARCHAR DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS learning_profiles (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR NOT NULL,
    proficiency_level VARCHAR DEFAULT 'beginner',
    mastery_score DOUBLE PRECISION DEFAULT 0.0,
    topics_completed INTEGER DEFAULT 0,
    total_questions_answered INTEGER DEFAULT 0,
    correct_answers INTEGER DEFAULT 0,
    last_active TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, subject)
);

CREATE TABLE IF NOT EXISTS chat_sessions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR DEFAULT 'general',
    title VARCHAR DEFAULT 'New Chat',
    language VARCHAR DEFAULT 'de',
    messages TEXT DEFAULT '[]',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quiz_results (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR NOT NULL,
    quiz_type VARCHAR DEFAULT 'mcq',
    total_questions INTEGER DEFAULT 0,
    correct_answers INTEGER DEFAULT 0,
    score DOUBLE PRECISION DEFAULT 0.0,
    difficulty VARCHAR DEFAULT 'intermediate',
    questions TEXT DEFAULT '[]',
    completed_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS learning_resources (
    id SERIAL PRIMARY KEY,
    subject VARCHAR NOT NULL,
    topic VARCHAR NOT NULL,
    content TEXT NOT NULL,
    difficulty VARCHAR DEFAULT 'intermediate',
    grade_level VARCHAR DEFAULT '10',
    language VARCHAR DEFAULT 'de',
    metadata TEXT DEFAULT '{}',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quiz_answers (
    id SERIAL PRIMARY KEY,
    quiz_id VARCHAR NOT NULL,
    question_id INTEGER NOT NULL,
    correct_answer VARCHAR NOT NULL,
    explanation VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(quiz_id, question_id)
);

CREATE TABLE IF NOT EXISTS activity_log (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    activity_type VARCHAR NOT NULL,
    subject VARCHAR DEFAULT 'general',
    description VARCHAR DEFAULT '',
    metadata TEXT DEFAULT '{}',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_memories (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    topic_id VARCHAR NOT NULL,
    subject VARCHAR NOT NULL,
    topic_name VARCHAR DEFAULT '',
    schwach INTEGER DEFAULT 0,
    feedback_score INTEGER DEFAULT 0,
    times_asked INTEGER DEFAULT 0,
    times_correct INTEGER DEFAULT 0,
    letzte_frage TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, topic_id)
);

CREATE TABLE IF NOT EXISTS abitur_simulations (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR NOT NULL,
    duration_minutes INTEGER DEFAULT 180,
    start_time TIMESTAMP DEFAULT NOW(),
    pause_time VARCHAR DEFAULT '',
    paused_elapsed_seconds INTEGER DEFAULT 0,
    score DOUBLE PRECISION DEFAULT 0.0,
    note_punkte INTEGER DEFAULT 0,
    status VARCHAR DEFAULT 'active',
    questions TEXT DEFAULT '[]',
    answers TEXT DEFAULT '[]',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wochen_coach_plans (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR NOT NULL,
    plan_json TEXT DEFAULT '[]',
    week_count INTEGER DEFAULT 8,
    current_week INTEGER DEFAULT 1,
    status VARCHAR DEFAULT 'active',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gamification (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    xp INTEGER DEFAULT 0,
    level INTEGER DEFAULT 1,
    level_name VARCHAR DEFAULT 'Neuling',
    streak_days INTEGER DEFAULT 0,
    streak_last_date VARCHAR DEFAULT '',
    quizzes_completed INTEGER DEFAULT 0,
    chats_sent INTEGER DEFAULT 0,
    abitur_completed INTEGER DEFAULT 0,
    achievements TEXT DEFAULT '[]',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS group_chats (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    subject VARCHAR DEFAULT 'general',
    created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    members TEXT DEFAULT '[]',
    messages TEXT DEFAULT '[]',
    max_members INTEGER DEFAULT 10,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS research_results (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    query VARCHAR NOT NULL,
    results_json TEXT DEFAULT '[]',
    source_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS coupons (
    id SERIAL PRIMARY KEY,
    code VARCHAR UNIQUE NOT NULL,
    tier VARCHAR NOT NULL DEFAULT 'pro',
    duration_days INTEGER NOT NULL DEFAULT 30,
    max_uses INTEGER DEFAULT 0,
    current_uses INTEGER DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    created_by INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS coupon_redemptions (
    id SERIAL PRIMARY KEY,
    coupon_id INTEGER NOT NULL REFERENCES coupons(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    redeemed_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(coupon_id, user_id)
);

CREATE TABLE IF NOT EXISTS tournaments (
    id SERIAL PRIMARY KEY,
    subject VARCHAR NOT NULL,
    date VARCHAR NOT NULL,
    status VARCHAR DEFAULT 'scheduled',
    questions TEXT DEFAULT '[]',
    num_questions INTEGER DEFAULT 20,
    time_limit_seconds INTEGER DEFAULT 300,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tournament_entries (
    id SERIAL PRIMARY KEY,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    score INTEGER DEFAULT 0,
    correct_answers INTEGER DEFAULT 0,
    time_taken_seconds INTEGER DEFAULT 0,
    answers TEXT DEFAULT '[]',
    submitted_at VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(tournament_id, user_id)
);

CREATE TABLE IF NOT EXISTS admin_logs (
    id SERIAL PRIMARY KEY,
    admin_id INTEGER NOT NULL REFERENCES users(id),
    action VARCHAR NOT NULL,
    target_user_id INTEGER,
    details VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iq_tests (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    questions TEXT DEFAULT '[]',
    num_questions INTEGER DEFAULT 40,
    time_limit_seconds INTEGER DEFAULT 2700,
    status VARCHAR DEFAULT 'active',
    submitted_at VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iq_results (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    test_id INTEGER NOT NULL REFERENCES iq_tests(id),
    iq_score INTEGER DEFAULT 100,
    iq_range VARCHAR DEFAULT '',
    percentile INTEGER DEFAULT 50,
    klassifikation VARCHAR DEFAULT '',
    kategorien TEXT DEFAULT '{}',
    staerken TEXT DEFAULT '[]',
    schwaechen TEXT DEFAULT '[]',
    raw_score DOUBLE PRECISION DEFAULT 0.0,
    max_score DOUBLE PRECISION DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_feedback (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id INTEGER NOT NULL,
    message_index INTEGER NOT NULL,
    rating VARCHAR NOT NULL DEFAULT 'positive',
    reason VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS multiplayer_rooms (
    id SERIAL PRIMARY KEY,
    room_code VARCHAR UNIQUE NOT NULL,
    host_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR DEFAULT 'general',
    topic VARCHAR DEFAULT '',
    status VARCHAR DEFAULT 'waiting',
    max_players INTEGER DEFAULT 8,
    num_questions INTEGER DEFAULT 10,
    questions TEXT DEFAULT '[]',
    players TEXT DEFAULT '[]',
    scores TEXT DEFAULT '{}',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS school_licenses (
    id SERIAL PRIMARY KEY,
    school_name VARCHAR NOT NULL,
    teacher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    class_code VARCHAR UNIQUE NOT NULL,
    tier VARCHAR DEFAULT 'max',
    max_students INTEGER DEFAULT 30,
    students TEXT DEFAULT '[]',
    is_active INTEGER DEFAULT 1,
    expires_at VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS push_subscriptions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint VARCHAR NOT NULL,
    p256dh VARCHAR DEFAULT '',
    auth_key VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, endpoint)
);

CREATE TABLE IF NOT EXISTS pomodoro_sessions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR DEFAULT 'general',
    duration_minutes INTEGER DEFAULT 25,
    xp_earned INTEGER DEFAULT 25,
    completed_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shop_purchases (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_id VARCHAR NOT NULL,
    item_name VARCHAR DEFAULT '',
    category VARCHAR DEFAULT '',
    price_xp INTEGER DEFAULT 0,
    purchased_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS challenges_db (
    id SERIAL PRIMARY KEY,
    challenge_id VARCHAR UNIQUE NOT NULL,
    creator_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR NOT NULL,
    description VARCHAR DEFAULT '',
    subject VARCHAR DEFAULT 'general',
    target_score INTEGER DEFAULT 80,
    xp_reward INTEGER DEFAULT 100,
    deadline VARCHAR DEFAULT '',
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS challenge_progress (
    id SERIAL PRIMARY KEY,
    challenge_id VARCHAR NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR DEFAULT 'joined',
    score INTEGER DEFAULT 0,
    completed_at VARCHAR DEFAULT '',
    joined_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(challenge_id, user_id)
);

CREATE TABLE IF NOT EXISTS spaced_repetition (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR NOT NULL,
    topic VARCHAR NOT NULL,
    next_review TIMESTAMP DEFAULT NOW(),
    interval_days INTEGER DEFAULT 1,
    ease_factor DOUBLE PRECISION DEFAULT 2.5,
    repetitions INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, subject, topic)
);

CREATE TABLE IF NOT EXISTS daily_quests (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    quest_id VARCHAR NOT NULL,
    quest_date VARCHAR NOT NULL,
    title VARCHAR NOT NULL,
    description VARCHAR DEFAULT '',
    xp_reward INTEGER DEFAULT 50,
    target INTEGER DEFAULT 1,
    progress INTEGER DEFAULT 0,
    completed INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, quest_id, quest_date)
);

CREATE TABLE IF NOT EXISTS parent_links (
    id SERIAL PRIMARY KEY,
    parent_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    child_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    verified INTEGER DEFAULT 0,
    verification_token VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(parent_id, child_id)
);

CREATE TABLE IF NOT EXISTS seasonal_events (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR DEFAULT '',
    event_type VARCHAR DEFAULT 'challenge',
    start_date VARCHAR NOT NULL,
    end_date VARCHAR NOT NULL,
    rewards_json TEXT DEFAULT '{}',
    challenges_json TEXT DEFAULT '[]',
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ki_relationship (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    trust_level DOUBLE PRECISION DEFAULT 1.0,
    known_name VARCHAR DEFAULT '',
    known_hobbies TEXT DEFAULT '[]',
    preferred_explanation VARCHAR DEFAULT 'Analogien',
    difficult_topics TEXT DEFAULT '[]',
    interaction_count INTEGER DEFAULT 0,
    last_interaction TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    last_emotion VARCHAR DEFAULT '',
    erfolge_erwaehnt TEXT DEFAULT '[]',
    lieblingserklaerung VARCHAR DEFAULT 'Analogien'
);

CREATE TABLE IF NOT EXISTS marketplace_items (
    id SERIAL PRIMARY KEY,
    creator_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR NOT NULL,
    description VARCHAR DEFAULT '',
    price_cents INTEGER DEFAULT 0,
    item_type VARCHAR DEFAULT 'quiz_set',
    content_json TEXT DEFAULT '[]',
    downloads INTEGER DEFAULT 0,
    rating DOUBLE PRECISION DEFAULT 0.0,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notifications (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR NOT NULL DEFAULT '',
    message VARCHAR NOT NULL DEFAULT '',
    type VARCHAR DEFAULT 'info',
    is_read INTEGER DEFAULT 0,
    link VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS flashcards (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR DEFAULT 'general',
    front VARCHAR NOT NULL DEFAULT '',
    back VARCHAR NOT NULL DEFAULT '',
    difficulty INTEGER DEFAULT 0,
    next_review TIMESTAMP DEFAULT NOW(),
    interval_days INTEGER DEFAULT 1,
    ease_factor DOUBLE PRECISION DEFAULT 2.5,
    repetitions INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS xp_log (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL DEFAULT 0,
    source VARCHAR DEFAULT '',
    description VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS question_history (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fach VARCHAR NOT NULL,
    thema VARCHAR DEFAULT '',
    frage_hash VARCHAR NOT NULL,
    gesehen_am TIMESTAMP DEFAULT NOW(),
    richtig INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS noten_prognose (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fach VARCHAR NOT NULL,
    aktuelle_note DOUBLE PRECISION,
    prognose_note DOUBLE PRECISION,
    trend VARCHAR DEFAULT 'stabil',
    confidence DOUBLE PRECISION DEFAULT 0.5,
    analyse TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS battle_pass (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    saison VARCHAR DEFAULT 'Fruehling 2026',
    current_level INTEGER DEFAULT 1,
    current_xp INTEGER DEFAULT 0,
    xp_per_level INTEGER DEFAULT 200,
    claimed_rewards TEXT DEFAULT '[]',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS parent_link_requests (
    id SERIAL PRIMARY KEY,
    parent_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    child_email VARCHAR NOT NULL,
    token VARCHAR UNIQUE NOT NULL,
    status VARCHAR DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS marketplace_purchases (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES marketplace_items(id),
    payment_intent_id VARCHAR DEFAULT '',
    amount_cents INTEGER DEFAULT 0,
    status VARCHAR DEFAULT 'completed',
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, item_id)
);

CREATE TABLE IF NOT EXISTS schulbuch_scans (
    id SERIAL PRIMARY KEY,
    scan_id VARCHAR UNIQUE NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fach VARCHAR DEFAULT 'Allgemein',
    ocr_text TEXT DEFAULT '',
    analyse TEXT DEFAULT '{}',
    quiz TEXT DEFAULT '[]',
    karteikarten TEXT DEFAULT '[]',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ws_tickets (
    id SERIAL PRIMARY KEY,
    ticket VARCHAR UNIQUE NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quiz_confidence (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    quiz_id INTEGER,
    fach VARCHAR DEFAULT 'Allgemein',
    thema VARCHAR DEFAULT '',
    confidence INTEGER DEFAULT 3,
    war_richtig INTEGER DEFAULT 0,
    blind_spot INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lehrplan_themen (
    id SERIAL PRIMARY KEY,
    fach VARCHAR NOT NULL,
    bundesland VARCHAR DEFAULT '',
    themen TEXT DEFAULT '[]',
    quelle VARCHAR DEFAULT '',
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(fach, bundesland)
);

CREATE TABLE IF NOT EXISTS knowledge_updates (
    id SERIAL PRIMARY KEY,
    fach VARCHAR NOT NULL,
    thema VARCHAR NOT NULL,
    quellen_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS prompt_vorschlaege (
    id SERIAL PRIMARY KEY,
    fach VARCHAR NOT NULL,
    probleme VARCHAR DEFAULT '',
    neuer_prompt TEXT DEFAULT '',
    feedback_count INTEGER DEFAULT 0,
    status VARCHAR DEFAULT 'ausstehend',
    created_at TIMESTAMP DEFAULT NOW(),
    genehmigt_am VARCHAR DEFAULT ''
);

CREATE TABLE IF NOT EXISTS chat_feedbacks_v2 (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message_id VARCHAR DEFAULT '',
    frage VARCHAR DEFAULT '',
    antwort TEXT DEFAULT '',
    bewertung VARCHAR DEFAULT 'positiv',
    fach VARCHAR DEFAULT '',
    kommentar VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS weekly_challenges (
    id SERIAL PRIMARY KEY,
    challenge_id VARCHAR UNIQUE NOT NULL,
    title VARCHAR NOT NULL,
    description VARCHAR DEFAULT '',
    subject VARCHAR DEFAULT 'general',
    target_score INTEGER DEFAULT 80,
    xp_reward INTEGER DEFAULT 150,
    deadline VARCHAR DEFAULT '',
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shop_rotations (
    id SERIAL PRIMARY KEY,
    week_date VARCHAR NOT NULL UNIQUE,
    items_json TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS prompt_improvements (
    id SERIAL PRIMARY KEY,
    fach VARCHAR NOT NULL,
    verbesserung TEXT NOT NULL,
    fehler_count INTEGER DEFAULT 0,
    applied INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ══════════════════════════════════════════════════
-- Performance Indexes
-- ══════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_clerk_id ON users(clerk_user_id);
CREATE INDEX IF NOT EXISTS idx_users_tier ON users(subscription_tier);
CREATE INDEX IF NOT EXISTS idx_quiz_results_user ON quiz_results(user_id, completed_at);
CREATE INDEX IF NOT EXISTS idx_quiz_results_subject ON quiz_results(user_id, subject);
CREATE INDEX IF NOT EXISTS idx_activity_log_user ON activity_log(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_activity_log_type ON activity_log(user_id, activity_type, created_at);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_user ON chat_sessions(user_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_gamification_user ON gamification(user_id);
CREATE INDEX IF NOT EXISTS idx_tournaments_date ON tournaments(date, status);
CREATE INDEX IF NOT EXISTS idx_tournament_entries_user ON tournament_entries(user_id, tournament_id);
CREATE INDEX IF NOT EXISTS idx_daily_quests_user ON daily_quests(user_id, quest_date);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, is_read, created_at);
CREATE INDEX IF NOT EXISTS idx_spaced_repetition_review ON spaced_repetition(user_id, next_review);
CREATE INDEX IF NOT EXISTS idx_flashcards_review ON flashcards(user_id, next_review);
CREATE INDEX IF NOT EXISTS idx_ki_relationship_user ON ki_relationship(user_id);
CREATE INDEX IF NOT EXISTS idx_question_history_user_fach ON question_history(user_id, fach, gesehen_am);
CREATE INDEX IF NOT EXISTS idx_battle_pass_user ON battle_pass(user_id);
CREATE INDEX IF NOT EXISTS idx_xp_log_user ON xp_log(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_noten_prognose_user ON noten_prognose(user_id, fach);
CREATE INDEX IF NOT EXISTS idx_schulbuch_scans_user ON schulbuch_scans(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ws_tickets_ticket ON ws_tickets(ticket, expires_at);
CREATE INDEX IF NOT EXISTS idx_quiz_confidence_user ON quiz_confidence(user_id, fach, blind_spot);
CREATE INDEX IF NOT EXISTS idx_chat_feedbacks_v2_fach ON chat_feedbacks_v2(fach, bewertung, created_at);
CREATE INDEX IF NOT EXISTS idx_weekly_challenges_active ON weekly_challenges(is_active, deadline);
CREATE INDEX IF NOT EXISTS idx_shop_rotations_week ON shop_rotations(week_date);
CREATE INDEX IF NOT EXISTS idx_knowledge_updates_date ON knowledge_updates(created_at);
CREATE INDEX IF NOT EXISTS idx_prompt_vorschlaege_status ON prompt_vorschlaege(status);
"""


def run_migration(database_url: str) -> None:
    """Execute all PostgreSQL CREATE TABLE statements against the given database."""
    import psycopg2

    logger.info("Connecting to PostgreSQL: %s...", database_url[:40] + "...")

    conn = psycopg2.connect(database_url)
    conn.autocommit = False
    cursor = conn.cursor()

    try:
        # Split into individual statements and execute
        statements = [
            s.strip()
            for s in POSTGRES_TABLES.split(";")
            if s.strip() and not s.strip().startswith("--")
        ]

        success = 0
        errors = 0
        for stmt in statements:
            if not stmt or stmt.startswith("--"):
                continue
            try:
                cursor.execute(stmt + ";")
                success += 1
            except Exception as e:
                # Log but continue — some tables may already exist
                logger.warning("Statement fehlgeschlagen: %s... → %s", stmt[:60], e)
                conn.rollback()
                errors += 1

        conn.commit()
        logger.info(
            "Migration abgeschlossen: %d erfolgreich, %d Fehler (von %d Statements)",
            success, errors, len(statements),
        )

        # Count tables created
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.tables "
            "WHERE table_schema = 'public'"
        )
        table_count = cursor.fetchone()[0]
        logger.info("Tabellen in der Datenbank: %d", table_count)

    except Exception as e:
        conn.rollback()
        logger.error("Migration fehlgeschlagen: %s", e)
        raise
    finally:
        cursor.close()
        conn.close()


def main():
    """Entry point — read DATABASE_URL from env and run migration."""
    database_url = os.getenv("DATABASE_URL", "")
    if not database_url:
        logger.error(
            "DATABASE_URL nicht gesetzt!\n"
            "Beispiel: DATABASE_URL='postgresql://user:pass@host:5432/dbname' "
            "python scripts/supabase_setup.py"
        )
        sys.exit(1)

    if not database_url.startswith("postgresql"):
        logger.error("DATABASE_URL muss mit 'postgresql' beginnen!")
        sys.exit(1)

    run_migration(database_url)
    logger.info("Supabase Setup abgeschlossen!")


if __name__ == "__main__":
    main()
