"""Vollständige Fächer-Datenbank: 32 Fächer in 6 Kategorien.

LUMNOS Fächer-Expansion 5.0 Block 1:
- 32 subjects organized in 6 categories
- 50+ topics per new subject
- Metadata: kategorie, emoji, pflicht, spezial mode
"""

# ── ALLE 32 FAECHER ──────────────────────────────────────────
ALLE_FAECHER: dict[str, dict] = {
    # ── SPRACHEN ──────────────────────────────────────────
    "Deutsch": {"kategorie": "Sprachen", "emoji": "\U0001f4d6", "pflicht": True},
    "Englisch": {"kategorie": "Sprachen", "emoji": "\U0001f1ec\U0001f1e7", "pflicht": True},
    "Französisch": {"kategorie": "Sprachen", "emoji": "\U0001f1eb\U0001f1f7", "pflicht": False},
    "Latein": {
        "kategorie": "Sprachen",
        "emoji": "\U0001f3db\ufe0f",
        "pflicht": False,
        "spezial": "latein_modus",
    },
    "Spanisch": {"kategorie": "Sprachen", "emoji": "\U0001f1ea\U0001f1f8", "pflicht": False},
    "Italienisch": {"kategorie": "Sprachen", "emoji": "\U0001f1ee\U0001f1f9", "pflicht": False},
    "Russisch": {"kategorie": "Sprachen", "emoji": "\U0001f1f7\U0001f1fa", "pflicht": False},
    "Türkisch": {"kategorie": "Sprachen", "emoji": "\U0001f1f9\U0001f1f7", "pflicht": False},
    "Altgriechisch": {
        "kategorie": "Sprachen",
        "emoji": "\U0001f3fa",
        "pflicht": False,
        "spezial": "latein_modus",
    },
    # ── MINT ──────────────────────────────────────────────
    "Mathe": {"kategorie": "MINT", "emoji": "\U0001f4d0", "pflicht": True},
    "Physik": {"kategorie": "MINT", "emoji": "\u26a1", "pflicht": True},
    "Chemie": {"kategorie": "MINT", "emoji": "\U0001f9ea", "pflicht": True},
    "Biologie": {"kategorie": "MINT", "emoji": "\U0001f9ec", "pflicht": True},
    "Informatik": {"kategorie": "MINT", "emoji": "\U0001f4bb", "pflicht": False},
    "Astronomie": {"kategorie": "MINT", "emoji": "\U0001f52d", "pflicht": False},
    "Technik": {"kategorie": "MINT", "emoji": "\u2699\ufe0f", "pflicht": False},
    # ── GESELLSCHAFT ──────────────────────────────────────
    "Geschichte": {"kategorie": "Gesellschaft", "emoji": "\U0001f3db\ufe0f", "pflicht": True},
    "Geografie": {"kategorie": "Gesellschaft", "emoji": "\U0001f30d", "pflicht": True},
    "Politik": {"kategorie": "Gesellschaft", "emoji": "\U0001f5f3\ufe0f", "pflicht": False},
    "Wirtschaft": {"kategorie": "Gesellschaft", "emoji": "\U0001f4c8", "pflicht": False},
    "Psychologie": {"kategorie": "Gesellschaft", "emoji": "\U0001f9e0", "pflicht": False},
    "Pädagogik": {"kategorie": "Gesellschaft", "emoji": "\U0001f468\u200d\U0001f3eb", "pflicht": False},
    "Sozialwissenschaften": {"kategorie": "Gesellschaft", "emoji": "\U0001f465", "pflicht": False},
    "Philosophie": {"kategorie": "Gesellschaft", "emoji": "\U0001f4ad", "pflicht": False},
    "Recht": {"kategorie": "Gesellschaft", "emoji": "\u2696\ufe0f", "pflicht": False},
    # ── RELIGION & ETHIK ──────────────────────────────────
    "Religion (Kath.)": {"kategorie": "Religion & Ethik", "emoji": "\u271d\ufe0f", "pflicht": False},
    "Religion (Ev.)": {"kategorie": "Religion & Ethik", "emoji": "\u271d\ufe0f", "pflicht": False},
    "Islamunterricht": {"kategorie": "Religion & Ethik", "emoji": "\u262a\ufe0f", "pflicht": False},
    "Ethik": {"kategorie": "Religion & Ethik", "emoji": "\u2696\ufe0f", "pflicht": False},
    "Werte und Normen": {"kategorie": "Religion & Ethik", "emoji": "\U0001f4dc", "pflicht": False},
    # ── KREATIV ───────────────────────────────────────────
    "Kunst": {"kategorie": "Kreativ", "emoji": "\U0001f3a8", "pflicht": False},
    "Musik": {"kategorie": "Kreativ", "emoji": "\U0001f3b5", "pflicht": False},
    "Darstellendes Spiel": {"kategorie": "Kreativ", "emoji": "\U0001f3ad", "pflicht": False},
    "Sport": {"kategorie": "Kreativ", "emoji": "\u26bd", "pflicht": False},
    # ── HAUSHALT ──────────────────────────────────────────
    "Hauswirtschaft": {"kategorie": "Haushalt", "emoji": "\U0001f373", "pflicht": False},
    "Ernährungslehre": {"kategorie": "Haushalt", "emoji": "\U0001f34e", "pflicht": False},
}

KATEGORIEN = [
    "Sprachen",
    "MINT",
    "Gesellschaft",
    "Religion & Ethik",
    "Kreativ",
    "Haushalt",
]

# ── 50+ THEMEN PRO NEUEM FACH ────────────────────────────────
THEMEN_ERWEITERUNG: dict[str, list[str]] = {
    "Latein": [
        "Substantiv-Deklination (a/o/kons.)",
        "Adjektiv-Deklination",
        "Verb-Konjugation Praesens",
        "Perfekt aktiv",
        "Imperfekt",
        "Plusquamperfekt",
        "Futur I und II",
        "Passiv Praesens",
        "Passiv Perfekt",
        "Konjunktiv Praesens",
        "Konjunktiv Imperfekt",
        "AcI (Accusativus cum Infinitivo)",
        "Ablativus Absolutus",
        "Participium Coniunctum",
        "NcI (Nominativus cum Infinitivo)",
        "Relativsätze",
        "Finalsätze (ut/ne)",
        "Kausalsätze (quod/quia/cum)",
        "Temporalsätze (cum/postquam/ubi)",
        "Konzessivsätze (quamquam/cum)",
        "Pronomen (Personal/Demonstrativ/Relativ)",
        "Steigerung der Adjektive",
        "Adverbien und Steigerung",
        "Deponentia",
        "Stammformen wichtiger Verben",
        "Gerundium und Gerundivum",
        "Supinum",
        "Oratio Obliqua (indirekte Rede)",
        "Konditional-Sätze (si/nisi)",
        "Caesar: De Bello Gallico",
        "Cicero: In Catilinam",
        "Ovid: Metamorphosen",
        "Vergil: Aeneis",
        "Seneca: Epistulae morales",
        "Plinius: Briefe",
        "Sallust: Coniuratio Catilinae",
        "Roemische Republik",
        "Roemisches Kaiserreich",
        "Roemische Gesellschaft und Alltag",
        "Roemisches Recht",
        "Roemische Religion und Mythologie",
        "Lateinische Stilistik (Chiasmus, Anapher)",
        "Metrische Analyse (Hexameter)",
        "Wortschatz: Familie und Verwandtschaft",
        "Wortschatz: Staat und Politik",
        "Wortschatz: Krieg und Militaer",
        "Wortschatz: Philosophie und Ethik",
        "Etymologie (lat. Wörter in modernen Sprachen)",
        "Übersetzungstechnik: Satzanalyse",
        "Übersetzungstechnik: Konstruktionen",
        "Abitur-Latein: Interpretation und Stilistik",
    ],
    "Spanisch": [
        "Presente de Indicativo",
        "Preterito Indefinido",
        "Preterito Imperfecto",
        "Preterito Perfecto",
        "Futuro Simple",
        "Condicional",
        "Subjuntivo Presente",
        "Subjuntivo Imperfecto",
        "Imperativo",
        "Ser vs Estar",
        "Por vs Para",
        "Pronombres (Directo/Indirecto)",
        "Reflexive Verben",
        "Gerundio und Perifrasis",
        "Comparativos y Superlativos",
        "Articulacion y Pronunciacion",
        "Vocabulario: Familia",
        "Vocabulario: Viajes",
        "Vocabulario: Comida",
        "Vocabulario: Trabajo",
        "Vocabulario: Medio Ambiente",
        "Vocabulario: Tecnologia",
        "Leseverstehen DELE B1",
        "Leseverstehen DELE B2",
        "Hoerverstehen",
        "Aufsatz schreiben",
        "Spanische Kultur und Geschichte",
        "Lateinamerika: Geografie und Kultur",
        "Spanische Literatur",
        "Redewendungen und Sprichwörter",
        "Grammatik: Relativsätze",
        "Grammatik: Bedingungssätze",
        "Grammatik: Passiv",
        "Grammatik: Indirekte Rede",
        "Textmediation Spanisch-Deutsch",
        "Muendliche Prüfung",
        "Abitur-Spanisch",
        "Wortschatz B1",
        "Wortschatz B2",
        "Landeskunde Spanien",
        "Landeskunde Mexiko",
        "Landeskunde Argentinien",
        "Dialekte und Varianten",
        "Geschaeftsspanisch",
        "Literaturanalyse",
        "Film und Medien",
        "Politisches Spanisch",
        "Umwelt und Nachhaltigkeit",
        "Migration und Identitaet",
        "Abitur-Klausur-Training",
    ],
    "Italienisch": [
        "Presente Indicativo",
        "Passato Prossimo",
        "Imperfetto",
        "Futuro Semplice",
        "Condizionale",
        "Congiuntivo Presente",
        "Imperativo",
        "Pronomi Diretti e Indiretti",
        "Articoli e Preposizioni",
        "Aggettivi e Comparativi",
        "Verbi Riflessivi",
        "Passivo",
        "Gerundio e Participio",
        "Periodo Ipotetico",
        "Discorso Indiretto",
        "Vocabulario: Famiglia",
        "Vocabulario: Cibo e Cucina",
        "Vocabulario: Viaggi",
        "Vocabulario: Lavoro",
        "Vocabulario: Arte e Cultura",
        "Leseverstehen Italienisch",
        "Hoerverstehen Italienisch",
        "Aufsatz Italienisch",
        "Italienische Kultur",
        "Italienische Geschichte",
        "Italienische Literatur (Dante, Petrarca)",
        "Landeskunde Italien",
        "Redewendungen",
        "Grammatik: Relativsätze",
        "Grammatik: Konjunktionen",
        "Aussprache und Intonation",
        "Textmediation Italienisch-Deutsch",
        "Abitur-Italienisch",
        "Wortschatz A2-B1",
        "Wortschatz B1-B2",
        "Italienische Musik",
        "Mode und Design",
        "Tourismus und Gastronomie",
        "Film (Cinema Italiano)",
        "Dialekte Italiens",
        "Geschaeftsitalienisch",
        "Muendliche Prüfung",
        "Umwelt und Gesellschaft",
        "Migration in Italien",
        "Europaeische Union",
        "Medien und Kommunikation",
        "Sport in Italien",
        "Renaissance",
        "Roemisches Erbe",
        "Moderne italienische Gesellschaft",
    ],
    "Russisch": [
        "Kyrillisches Alphabet",
        "Aussprache und Betonung",
        "Substantive: Genus und Deklination",
        "Adjektive: Deklination",
        "Verb-Konjugation (1./2. Konjugation)",
        "Aspekte: Vollendeter/Unvollendeter Aspekt",
        "Verben der Bewegung",
        "Pronomen (Personal/Possessiv/Demonstrativ)",
        "Zahlwörter",
        "Praepositionen und Kasus",
        "Wortstellung im Russischen",
        "Verneinung",
        "Imperativ",
        "Vergangenheitsformen",
        "Futur",
        "Konjunktiv/Konditional",
        "Passiv",
        "Partizipien",
        "Adverbien",
        "Vokabular: Familie",
        "Vokabular: Essen",
        "Vokabular: Reisen",
        "Vokabular: Schule/Uni",
        "Vokabular: Beruf",
        "Vokabular: Stadt und Natur",
        "Leseverstehen Russisch",
        "Hoerverstehen Russisch",
        "Russische Kultur und Feiertage",
        "Russische Geschichte (Zarenreich)",
        "Russische Geschichte (Sowjetunion)",
        "Russische Literatur (Puschkin, Tolstoi, Dostojewski)",
        "Russische Geografie",
        "Landeskunde Russland",
        "Redewendungen",
        "Geschriebenes vs Gesprochenes Russisch",
        "Russische Medien",
        "Textmediation Russisch-Deutsch",
        "Handschrift (Schreibschrift)",
        "Wortschatz A1-A2",
        "Wortschatz A2-B1",
        "Grammatik-Tabellen",
        "Muendliche Prüfung",
        "Abitur-Russisch",
        "Alltagskommunikation",
        "Russische Musik und Film",
        "Politik und Gesellschaft",
        "Wirtschaft Russlands",
        "Kunst und Architektur",
        "Russische Kueche",
        "Interkulturelles Lernen",
    ],
    "Türkisch": [
        "Türkisches Alphabet und Aussprache",
        "Vokalharmonie",
        "Substantive und Plural",
        "Possessivsuffixe",
        "Kasus (Akkusativ, Dativ, Lokativ, Ablativ)",
        "Adjektive",
        "Verben: Praesens",
        "Verben: Vergangenheit (di-Vergangenheit)",
        "Verben: Vergangenheit (mis-Vergangenheit)",
        "Verben: Futur",
        "Verneinung",
        "Fragesätze",
        "Postpositionen",
        "Konjunktionen",
        "Relativsätze auf Türkisch",
        "Passiv und Kausativ",
        "Reflexive Verben",
        "Konditional/Wunschform",
        "Indirekte Rede",
        "Vokabular: Familie",
        "Vokabular: Essen und Trinken",
        "Vokabular: Einkaufen",
        "Vokabular: Reisen",
        "Vokabular: Schule",
        "Vokabular: Beruf",
        "Vokabular: Gesundheit",
        "Leseverstehen Türkisch",
        "Hoerverstehen Türkisch",
        "Türkische Kultur und Traditionen",
        "Türkische Geschichte",
        "Landeskunde Tuerkei",
        "Türkische Literatur",
        "Türkische Medien",
        "Redewendungen und Sprichwörter",
        "Alltagskommunikation",
        "Türkische Musik und Film",
        "Textmediation Türkisch-Deutsch",
        "Grammatik: Suffixe und Agglutination",
        "Grammatik: Nominalgruppen",
        "Wortschatz A1-A2",
        "Wortschatz A2-B1",
        "Muendliche Prüfung",
        "Interkulturelles Lernen",
        "Migration und Identitaet",
        "Türkische Kueche",
        "Moderne Tuerkei",
        "Istanbul und andere Staedte",
        "Türkische Geografie",
        "Sport und Freizeit",
        "Abitur-Türkisch",
    ],
    "Altgriechisch": [
        "Griechisches Alphabet",
        "Akzente und Spiritus",
        "Substantiv-Deklination (o/a/kons.)",
        "Adjektiv-Deklination",
        "Artikel",
        "Verb-Konjugation Praesens",
        "Aorist",
        "Imperfekt",
        "Perfekt",
        "Futur",
        "Konjunktiv und Optativ",
        "Partizipien",
        "Infinitive",
        "Medium und Passiv",
        "Deponentia",
        "AcI und AcP",
        "Genitivus Absolutus",
        "Relativsätze",
        "Bedingungssätze",
        "Indirekte Rede",
        "Pronomen",
        "Zahlwörter",
        "Praepositionen mit Kasus",
        "Homer: Ilias",
        "Homer: Odyssee",
        "Platon: Apologie/Politeia",
        "Sophokles: Antigone/Oedipus",
        "Euripides: Medea",
        "Herodot: Historien",
        "Thukydides: Peloponnesischer Krieg",
        "Xenophon: Anabasis",
        "Griechische Mythologie",
        "Griechische Philosophie",
        "Griechische Demokratie (Athen)",
        "Sparta",
        "Perserkriege",
        "Alexander der Grosse",
        "Hellenismus",
        "Griechische Kunst und Architektur",
        "Griechisches Theater",
        "Olympische Spiele (antik)",
        "Griechische Religion",
        "Etymologie (griech. Wörter in modernen Sprachen)",
        "Metrische Analyse",
        "Stilistik und Rhetorik",
        "Textinterpretation",
        "Übersetzungstechnik",
        "Stammformen wichtiger Verben",
        "Wortschatz: Philosophie",
        "Wortschatz: Politik",
        "Abitur-Griechisch",
    ],
    "Astronomie": [
        "Sonnensystem: Aufbau und Planeten",
        "Sonne: Aufbau und Kernfusion",
        "Mond: Phasen und Gezeiten",
        "Sternbilder und Himmelsnavigation",
        "Sternentwicklung (Hauptreihe bis Supernova)",
        "Hertzsprung-Russell-Diagramm",
        "Galaxien: Typen und Aufbau",
        "Milchstrasse",
        "Schwarze Loecher",
        "Neutronensterne und Pulsare",
        "Weisse Zwerge",
        "Rote Riesen",
        "Nebel und Sternentstehung",
        "Exoplaneten und Habitabiliaet",
        "Kosmologie: Urknall-Theorie",
        "Expansion des Universums",
        "Dunkle Materie und Dunkle Energie",
        "Kosmische Hintergrundstrahlung",
        "Raumfahrt: Geschichte",
        "Raumfahrt: ISS und Raumstationen",
        "Raumfahrt: Mars-Missionen",
        "Keplersche Gesetze",
        "Gravitation und Orbitmechanik",
        "Licht: Spektralanalyse",
        "Entfernungsmessung (Parallaxe, Rotverschiebung)",
        "Asteroiden und Kometen",
        "Meteoriten und Einschlaege",
        "Radioastronomie",
        "Teleskope (optisch, IR, Radio)",
        "James-Webb-Weltraumteleskop",
        "Zeitrechnung und Kalender",
        "Astronomie in der Antike",
        "Kopernikus, Galilei, Kepler",
        "Einstein und Relativitaetstheorie",
        "Gravitationswellen",
        "Astrofotografie",
        "Leben im Universum (Astrobiologie)",
        "Sonnenwinde und Weltraumwetter",
        "Planetenringe",
        "Zwergplaneten (Pluto, Ceres, Eris)",
        "Kuiperguertel und Oortsche Wolke",
        "Multiversum-Hypothese",
        "Zeitdilatation",
        "Hubble-Konstante",
        "Zukunft des Universums",
        "Sonnen- und Mondfinsternisse",
        "Astronomie als Hobby",
        "Berufe in der Astronomie",
        "Beruehmte Observatorien",
        "Weltraummuell",
    ],
    "Technik": [
        "Werkstoffkunde: Metalle",
        "Werkstoffkunde: Kunststoffe",
        "Werkstoffkunde: Holz",
        "Technisches Zeichnen (CAD)",
        "Elektrotechnik Grundlagen",
        "Elektronik: Schaltungen",
        "Digitaltechnik",
        "Mikroprozessoren und Microcontroller",
        "Robotik Grundlagen",
        "3D-Druck und Additive Fertigung",
        "CNC-Technik",
        "Maschinenbau Grundlagen",
        "Thermodynamik in der Technik",
        "Erneuerbare Energien (Solar, Wind)",
        "Energietechnik und Kraftwerke",
        "Fahrzeugtechnik",
        "Elektromobilitaet",
        "Automatisierungstechnik",
        "Steuerungstechnik (SPS)",
        "Messtechnik und Sensorik",
        "Regelungstechnik",
        "Fertigungstechnik (Drehen, Fraesen, Bohren)",
        "Verbindungstechnik (Schrauben, Schweissen, Loeten)",
        "Hydraulik und Pneumatik",
        "Getriebe und Antriebstechnik",
        "Technische Mechanik: Statik",
        "Technische Mechanik: Dynamik",
        "Festigkeitslehre",
        "Waermelehre (technisch)",
        "Stroemungslehre",
        "Nachrichtentechnik",
        "Netzwerktechnik",
        "Smart Home und IoT",
        "Industrie 4.0",
        "Kuenstliche Intelligenz in der Technik",
        "Umwelttechnik",
        "Verpackungstechnik",
        "Lebensmitteltechnologie",
        "Textiltechnik",
        "Bautechnik Grundlagen",
        "Architektur und Konstruktion",
        "Brueckenbau und Tragwerke",
        "Verkehrstechnik",
        "Sicherheitstechnik",
        "Qualitaetsmanagement",
        "Projektmanagement in der Technik",
        "Patente und Erfindungen",
        "Geschichte der Technik",
        "Beruehmte Ingenieure und Erfinder",
        "Technik und Ethik",
    ],
    "Psychologie": [
        "Grundlagen der Psychologie",
        "Geschichte der Psychologie",
        "Behaviorismus (Watson, Skinner)",
        "Kognitivismus",
        "Psychoanalyse (Freud, Jung)",
        "Humanistische Psychologie (Rogers, Maslow)",
        "Entwicklungspsychologie: Kindheit",
        "Entwicklungspsychologie: Jugend",
        "Entwicklungspsychologie: Erwachsenenalter",
        "Piaget: Kognitive Entwicklung",
        "Erikson: Psychosoziale Entwicklung",
        "Kohlberg: Moralentwicklung",
        "Lernpsychologie: Klassische Konditionierung",
        "Lernpsychologie: Operante Konditionierung",
        "Lernpsychologie: Modelllernen (Bandura)",
        "Wahrnehmungspsychologie",
        "Gedaechtnispsychologie",
        "Denkpsychologie und Problemlösen",
        "Emotionspsychologie",
        "Motivationspsychologie (Maslow, Herzberg)",
        "Sozialpsychologie: Gruppenverhalten",
        "Sozialpsychologie: Konformitaet (Asch)",
        "Sozialpsychologie: Gehorsam (Milgram)",
        "Sozialpsychologie: Stanford-Prison",
        "Persönlichkeitspsychologie (Big Five)",
        "Klinische Psychologie: Angststoerungen",
        "Klinische Psychologie: Depression",
        "Klinische Psychologie: Essstoerungen",
        "Klinische Psychologie: ADHS",
        "Biopsychologie: Gehirn und Nervensystem",
        "Biopsychologie: Neurotransmitter",
        "Biopsychologie: Hormone",
        "Forschungsmethoden: Experiment",
        "Forschungsmethoden: Beobachtung",
        "Forschungsmethoden: Befragung",
        "Forschungsmethoden: Statistik",
        "Paedagogische Psychologie",
        "Arbeits- und Organisationspsychologie",
        "Medienpsychologie",
        "Gesundheitspsychologie",
        "Positive Psychologie",
        "Stressforschung und Coping",
        "Schlafforschung",
        "Bewusstsein und Unbewusstes",
        "Kreativitaet und Intelligenz",
        "Kommunikationspsychologie",
        "Kulturvergleichende Psychologie",
        "Forensische Psychologie",
        "Ethik in der Psychologie",
        "Abitur-Psychologie",
    ],
    "Pädagogik": [
        "Erziehungsstile (autoritaer, demokratisch, laissez-faire)",
        "Erziehungsziele und -normen",
        "Sozialisation: Primaer und Sekundaer",
        "Anlage-Umwelt-Debatte",
        "Piaget: Kognitive Entwicklung",
        "Erikson: Identitaetsentwicklung",
        "Kohlberg: Moralische Entwicklung",
        "Montessori-Pädagogik",
        "Waldorf-Pädagogik (Steiner)",
        "Reggio-Pädagogik",
        "Reformpaedagogik (Dewey, Freinet)",
        "Antiautoritaere Erziehung (Neill)",
        "Behavioristische Lerntheorien",
        "Kognitivistische Lerntheorien",
        "Konstruktivistische Lerntheorien",
        "Modelllernen nach Bandura",
        "Fruehkindliche Bildung",
        "Schulpaedagogik: Didaktik",
        "Schulpaedagogik: Unterrichtsplanung",
        "Inklusion und Foerderung",
        "Interkulturelle Pädagogik",
        "Medienpaedagogik",
        "Sexualpaedagogik",
        "Gewaltpraevention",
        "Bindungstheorie (Bowlby, Ainsworth)",
        "Resilienz und Risikofaktoren",
        "Jugendkriminalitaet",
        "Suchtpraevention",
        "Lernmotivation und Selbstregulation",
        "Leistungsbewertung und Diagnostik",
        "Begabtenfoerderung",
        "Lernbehinderung und Foerderschule",
        "Elternarbeit",
        "Erziehung in verschiedenen Kulturen",
        "Geschichte der Pädagogik",
        "Rousseau: Emile",
        "Pestalozzi und Froebel",
        "Bildung im 21. Jahrhundert",
        "Digitale Bildung",
        "Bildungsgerechtigkeit",
        "PISA-Studien und Bildungsvergleich",
        "Ganztagsschule und Betreuung",
        "Berufsorientierung",
        "Paedagogische Institutionen",
        "Jugendhilfe und Sozialarbeit",
        "Erziehungsberatung",
        "Paedagogische Ethik",
        "Erzieherausbildung",
        "Studium Erziehungswissenschaft",
        "Abitur-Pädagogik",
    ],
    "Sozialwissenschaften": [
        "Grundlagen der Soziologie",
        "Grundlagen der Politikwissenschaft",
        "Grundlagen der Wirtschaftswissenschaft",
        "Gesellschaftstheorien (Marx, Weber, Durkheim)",
        "Soziale Ungleichheit",
        "Soziale Schichtung und Mobilitaet",
        "Sozialstruktur Deutschlands",
        "Armut und Reichtum",
        "Demografischer Wandel",
        "Migration und Integration",
        "Familie im Wandel",
        "Jugendsoziologie",
        "Bildungssoziologie",
        "Mediensoziologie",
        "Digitalisierung und Gesellschaft",
        "Geschlechtersoziologie (Gender)",
        "Politisches System der BRD",
        "Grundgesetz und Verfassung",
        "Parteien und Wahlen",
        "Foederalismus",
        "Europaeische Union",
        "Internationale Beziehungen",
        "UNO und Voelkerrecht",
        "Friedens- und Konfliktforschung",
        "Globalisierung",
        "Soziale Marktwirtschaft",
        "Konjunktur und Wirtschaftspolitik",
        "Arbeitsmarkt und Arbeitslosigkeit",
        "Sozialpolitik und Sozialstaat",
        "Rentensystem",
        "Gesundheitssystem",
        "Umweltpolitik",
        "Klimawandel und Nachhaltigkeit",
        "Verbraucherbildung",
        "Forschungsmethoden Sozialwissenschaften",
        "Statistik und Datenanalyse",
        "Umfragen und Meinungsforschung",
        "Medien und Demokratie",
        "Populismus und Extremismus",
        "Terrorismus",
        "Menschenrechte",
        "Rassismus und Diskriminierung",
        "Zivilgesellschaft und Engagement",
        "Soziale Bewegungen",
        "Kommunalpolitik",
        "Landtags- und Bundespolitik",
        "Aktuelle politische Debatten",
        "Haushaltspolitik und Schulden",
        "Steuern und Abgaben",
        "Abitur-Sozialwissenschaften",
    ],
    "Philosophie": [
        "Was ist Philosophie?",
        "Vorsokratiker (Thales, Heraklit, Parmenides)",
        "Sokrates und die Maeeutik",
        "Platon: Ideenlehre und Hoehlengleichnis",
        "Aristoteles: Tugendethik und Logik",
        "Stoa (Seneca, Epiktet, Marc Aurel)",
        "Epikur: Lustethik",
        "Mittelalterliche Philosophie (Augustinus, Thomas v. A.)",
        "Descartes: Rationalismus (Cogito ergo sum)",
        "Locke, Hume: Empirismus",
        "Kant: Kritik der reinen Vernunft",
        "Kant: Kategorischer Imperativ",
        "Hegel: Dialektik",
        "Marx: Historischer Materialismus",
        "Nietzsche: Umwertung aller Werte",
        "Existenzialismus (Kierkegaard, Sartre, Camus)",
        "Utilitarismus (Bentham, Mill)",
        "Rawls: Theorie der Gerechtigkeit",
        "Habermas: Diskursethik",
        "Hannah Arendt: Banalitaet des Boesen",
        "Erkenntnistheorie: Was können wir wissen?",
        "Wissenschaftstheorie (Popper, Kuhn)",
        "Ethik: Grundbegriffe",
        "Angewandte Ethik: Medizinethik",
        "Angewandte Ethik: Tierethik",
        "Angewandte Ethik: Technikethik (KI)",
        "Angewandte Ethik: Umweltethik",
        "Politische Philosophie: Staatstheorien",
        "Politische Philosophie: Demokratie",
        "Politische Philosophie: Freiheit vs Sicherheit",
        "Sprachphilosophie (Wittgenstein)",
        "Philosophie des Geistes (Bewusstsein)",
        "Aesthetik und Kunstphilosophie",
        "Religionsphilosophie",
        "Logik: Grundlagen",
        "Logik: Fehlschluesse",
        "Argumentationstheorie",
        "Gedankenexperimente (Trolley-Problem, etc.)",
        "Philosophie und Naturwissenschaft",
        "Philosophie der Zeit",
        "Philosophie des Gluecks",
        "Feministische Philosophie",
        "Interkulturelle Philosophie",
        "Philosophie in Asien (Konfuzius, Buddha)",
        "Philosophie in Afrika",
        "Philosophie und Film",
        "Philosophie und Literatur",
        "Aktuelle philosophische Debatten",
        "Philosophie studieren",
        "Abitur-Philosophie",
    ],
    "Recht": [
        "Grundlagen des Rechts",
        "Oeffentliches Recht vs Privatrecht",
        "Grundgesetz und Grundrechte",
        "Menschenwürde (Art. 1 GG)",
        "Meinungsfreiheit (Art. 5 GG)",
        "Religionsfreiheit (Art. 4 GG)",
        "Gleichheitsgrundsatz (Art. 3 GG)",
        "Versammlungsfreiheit",
        "Berufsfreiheit",
        "Eigentumsrecht",
        "Strafrecht Grundlagen",
        "Strafrecht: Delikte (Diebstahl, Koerperverletzung)",
        "Jugendstrafrecht",
        "Zivilrecht: Vertragsrecht",
        "Zivilrecht: Kaufvertrag",
        "Zivilrecht: Maengelrecht",
        "Zivilrecht: Schadensersatz",
        "Arbeitsrecht Grundlagen",
        "Arbeitsvertrag und Kuendigung",
        "Familienrecht (Ehe, Scheidung, Sorgerecht)",
        "Erbrecht Grundlagen",
        "Mietrecht",
        "Internetrecht (Datenschutz, Urheberrecht)",
        "Medienrecht",
        "Umweltrecht",
        "Europarecht Grundlagen",
        "Voelkerrecht",
        "Gerichtsbarkeit in Deutschland",
        "Gerichtsverfahren: Ablauf",
        "Richter, Anwaelte, Staatsanwaelte",
        "Rechtsstaatsprinzip",
        "Gewaltenteilung",
        "Demokratieprinzip",
        "Sozialstaatsprinzip",
        "Foederalismus und Landesrecht",
        "Verwaltungsrecht",
        "Polizei- und Ordnungsrecht",
        "Wettbewerbsrecht",
        "Verbraucherschutz",
        "Datenschutz (DSGVO)",
        "Rechtsgeschichte",
        "Rechtsphilosophie",
        "Fallanalyse und Gutachtenstil",
        "Rechtssprechung (wichtige Urteile)",
        "Berufsbild Jurist/Juristin",
        "Studium der Rechtswissenschaft",
        "Aktuelle Rechtsdebatten",
        "Strafvollzug und Resozialisierung",
        "Opferschutz",
        "Abitur-Recht",
    ],
    "Religion (Kath.)": [
        "Gottesbild im AT und NT",
        "Jesus Christus: Leben und Wirken",
        "Gleichnisse Jesu",
        "Bergpredigt",
        "Auferstehung und Ostern",
        "Schoepfungsglaube und Naturwissenschaft",
        "Theodizee: Warum laesst Gott Leid zu?",
        "Christliche Ethik",
        "10 Gebote",
        "Sakramente",
        "Kirchengeschichte: Fruehes Christentum",
        "Kirchengeschichte: Mittelalter",
        "Kirchengeschichte: Reformation",
        "Kirchengeschichte: Neuzeit",
        "Katholische Soziallehre",
        "Oekumene: Einheit der Christen",
        "Interreligiöser Dialog",
        "Islam im Vergleich",
        "Judentum im Vergleich",
        "Buddhismus und Hinduismus",
        "Bibel: Aufbau und Interpretation",
        "Bibelexegese",
        "Prophetie",
        "Paulus und die Urgemeinde",
        "Heilige und Vorbilder",
        "Gebet und Liturgie",
        "Kirchenjahr und Feste",
        "Papst und Vatikan",
        "II. Vatikanisches Konzil",
        "Bioethik (Abtreibung, Sterbehilfe)",
        "Sozialethik und Gerechtigkeit",
        "Frieden und Gewalt",
        "Umweltethik (Laudato Si)",
        "Gewissen und Verantwortung",
        "Suche nach Sinn (V. Frankl)",
        "Tod und Auferstehung",
        "Eschatologie",
        "Religion und Wissenschaft",
        "Atheismus und Religionskritik",
        "Religion und Politik",
        "Religion und Medien",
        "Sekten und Neureligiositaet",
        "Religionsfreiheit",
        "Kirche in der modernen Gesellschaft",
        "Diakonie und Caritas",
        "Befreiungstheologie",
        "Mystik",
        "Kirchenmusik und Kunst",
        "Religion in der Literatur",
        "Abitur-Religion (kath.)",
    ],
    "Religion (Ev.)": [
        "Gottesbild: AT und NT",
        "Jesus Christus: Leben und Botschaft",
        "Gleichnisse und Wunder",
        "Bergpredigt und Nächstenliebe",
        "Kreuz und Auferstehung",
        "Schoepfung und Evolution",
        "Theodizee",
        "Rechtfertigung (sola fide, sola gratia)",
        "Martin Luther und Reformation",
        "Luthers 95 Thesen",
        "Evangelische Ethik",
        "10 Gebote (evangelische Deutung)",
        "Taufe und Abendmahl",
        "Kirchengeschichte (Urgemeinde bis heute)",
        "Dietrich Bonhoeffer",
        "Kirchenkampf im Nationalsozialismus",
        "Oekumene",
        "Interreligiöser Dialog",
        "Weltreligionen im Vergleich",
        "Bibel: Entstehung und Kanon",
        "Bibelhermeneutik",
        "Prophetie im AT",
        "Paulusbriefe",
        "Evangelische Kirchenstruktur",
        "EKD und Landeskirchen",
        "Diakonisches Werk",
        "Kirchentag",
        "Gebet und Gottesdienst",
        "Kirchenjahr",
        "Bioethik aus ev. Sicht",
        "Sozialethik: Armut und Reichtum",
        "Friedensethik",
        "Umweltethik",
        "Menschenbild und Würde",
        "Freiheit und Verantwortung",
        "Sinn des Lebens",
        "Tod und Hoffnung",
        "Religionskritik (Feuerbach, Marx, Nietzsche)",
        "Religion und Wissenschaft",
        "Religion und Gesellschaft",
        "Sekten und neue Religionen",
        "Spiritualitaet heute",
        "Feministische Theologie",
        "Befreiungstheologie",
        "Religion und Medien",
        "Kirchenmusik (Bach, Gesangbuch)",
        "Religion in Kunst und Literatur",
        "Diakonie und Ehrenamt",
        "Evangelische Jugendarbeit",
        "Abitur-Religion (ev.)",
    ],
    "Islamunterricht": [
        "Die fuenf Saeulen des Islam",
        "Shahada (Glaubensbekenntnis)",
        "Salat (Gebet)",
        "Zakat (Almosen)",
        "Saum (Fasten / Ramadan)",
        "Hadsch (Pilgerfahrt)",
        "Der Koran: Aufbau und Bedeutung",
        "Koranexegese (Tafsir)",
        "Prophet Muhammad: Leben",
        "Sunna und Hadith",
        "Islamische Geschichte: Fruehislam",
        "Islamische Geschichte: Goldenes Zeitalter",
        "Islamische Geschichte: Osmanen",
        "Islamisches Recht (Scharia Grundlagen)",
        "Islamische Ethik",
        "Gottesbild im Islam",
        "Engel und Propheten",
        "Jenseitsvorstellungen",
        "Islamische Feste (Eid al-Fitr, Eid al-Adha)",
        "Moschee: Aufbau und Bedeutung",
        "Islamische Kunst und Architektur",
        "Islamische Wissenschaft und Philosophie",
        "Dialog der Religionen",
        "Islam und Christentum",
        "Islam und Judentum",
        "Islam in Deutschland",
        "Muslimisches Leben im Alltag",
        "Halal und Haram",
        "Islamische Bekleidung (Kopftuch-Debatte)",
        "Frauen im Islam",
        "Jugend und Islam",
        "Islam und Demokratie",
        "Islam und Menschenrechte",
        "Islamismus vs Islam",
        "Praevention gegen Radikalisierung",
        "Sufismus (islamische Mystik)",
        "Sunniten und Schiiten",
        "Islamische Gelehrte",
        "Koranrezitation (Tajwid)",
        "Arabische Sprache Grundlagen",
        "Islamische Wirtschaftsethik",
        "Umweltethik im Islam",
        "Bioethik im Islam",
        "Friedensethik im Islam",
        "Islam und Wissenschaft",
        "Islam und Medien",
        "Interkulturelles Zusammenleben",
        "Integration und Identitaet",
        "Islamische Erziehung",
        "Abitur-Islamunterricht",
    ],
    "Werte und Normen": [
        "Was sind Werte und Normen?",
        "Moralisches Urteilen",
        "Ethische Grundpositionen",
        "Pflichtethik (Kant)",
        "Utilitarismus (Bentham, Mill)",
        "Tugendethik (Aristoteles)",
        "Diskursethik (Habermas)",
        "Verantwortungsethik (Jonas)",
        "Menschenwürde und Menschenrechte",
        "Freiheit und Verantwortung",
        "Gerechtigkeit (Rawls)",
        "Gewissen: Entwicklung und Bedeutung",
        "Kohlbergs Stufenmodell",
        "Identitaet und Selbstfindung",
        "Sinnfrage und Lebensentwuerfe",
        "Glueck und gutes Leben",
        "Freundschaft und Liebe",
        "Tod und Trauer",
        "Religionen im Vergleich",
        "Religionskritik",
        "Atheismus und Agnostizismus",
        "Naturethik und Umweltschutz",
        "Tierethik",
        "Bioethik: Gentechnik",
        "Bioethik: Sterbehilfe",
        "Bioethik: Organspende",
        "Medienethik",
        "Technikethik (KI, Roboter)",
        "Wirtschaftsethik",
        "Wissenschaftsethik",
        "Krieg und Frieden",
        "Todesstrafe",
        "Soziale Ungleichheit",
        "Rassismus und Diskriminierung",
        "Gender und Gleichberechtigung",
        "Toleranz und Respekt",
        "Demokratie und Menschenrechte",
        "Grundgesetz und Werte",
        "Interkulturalitaet",
        "Globalisierung und Verantwortung",
        "Gedankenexperimente (Trolley-Problem)",
        "Dilemma-Diskussionen",
        "Philosophische Texte interpretieren",
        "Argumentieren und Debattieren",
        "Medienkompetenz",
        "Konsumverhalten",
        "Nachhaltigkeit",
        "Zivilcourage",
        "Ehrenamt und Engagement",
        "Abitur-Werte und Normen",
    ],
    "Darstellendes Spiel": [
        "Grundlagen der Theaterarbeit",
        "Koerperarbeit und Bewegung",
        "Stimmbildung und Sprechtechnik",
        "Improvisation",
        "Rollenarbeit und Figurenentwicklung",
        "Szenisches Schreiben",
        "Dramaturgie",
        "Regie und Inszenierung",
        "Buehnengestaltung",
        "Licht und Ton",
        "Kostuem und Maske",
        "Theatergeschichte: Antike",
        "Theatergeschichte: Mittelalter/Barock",
        "Theatergeschichte: Klassik/Romantik",
        "Theatergeschichte: Modernes Theater",
        "Brecht: Episches Theater",
        "Stanislavski: Methode",
        "Artaud: Theater der Grausamkeit",
        "Grotowski: Armes Theater",
        "Postdramatisches Theater",
        "Musical und Musiktheater",
        "Tanztheater (Pina Bausch)",
        "Pantomime",
        "Figurentheater (Puppentheater)",
        "Kabarett und Comedy",
        "Strassentheater",
        "Theater und Politik",
        "Theater und Gesellschaft",
        "Theaterpaedagogik",
        "Gruppenprozesse im Theater",
        "Auftrittspraxis",
        "Lampenfieber ueberwinden",
        "Aufwaermübungen",
        "Vertrauensübungen",
        "Statusspiele",
        "Forumtheater (Boal)",
        "Szenische Interpretation",
        "Theaterbesuch: Nachbereitung",
        "Theaterkritik schreiben",
        "Dramenanalyse für DS",
        "Performance Art",
        "Theater und Film (Unterschiede)",
        "Theater und digitale Medien",
        "Theater im oeffentlichen Raum",
        "Theaterberufe",
        "Regiekonzept erstellen",
        "Probenarbeit organisieren",
        "Ensemble und Teamarbeit",
        "Aufnahmeprüfung Schauspielschule",
        "Abitur-Darstellendes Spiel",
    ],
    "Hauswirtschaft": [
        "Ernährungslehre Grundlagen",
        "Naehrstoffe: Kohlenhydrate",
        "Naehrstoffe: Fette",
        "Naehrstoffe: Eiweisse",
        "Vitamine und Mineralstoffe",
        "Ernährungspyramide",
        "Gesunde Ernährung im Alltag",
        "Lebensmittelkunde: Obst und Gemuese",
        "Lebensmittelkunde: Getreide",
        "Lebensmittelkunde: Milchprodukte",
        "Lebensmittelkunde: Fleisch und Fisch",
        "Lebensmittelkennzeichnung",
        "Lebensmittelhygiene (HACCP)",
        "Lebensmittellagerung",
        "Lebensmittelkonservierung",
        "Kochtechniken Grundlagen",
        "Backen Grundlagen",
        "Rezepte lesen und umsetzen",
        "Kuechengeraete und Werkzeuge",
        "Arbeitsplatzgestaltung Kueche",
        "Speiseplanung und Einkauf",
        "Nachhaltiger Konsum",
        "Saisonale und regionale Kueche",
        "Vegetarische/Vegane Ernährung",
        "Allergien und Unvertraeglichkeiten",
        "Ernährung in verschiedenen Kulturen",
        "Tischkultur und Tischdecken",
        "Waesche und Textilpflege",
        "Wohnraumgestaltung",
        "Reinigung und Haushaltspflege",
        "Abfallvermeidung und Recycling",
        "Budgetplanung (Haushaltsbuch)",
        "Verbraucherschutz",
        "Werbung und Konsum",
        "Nachhaltigkeit im Haushalt",
        "Energiesparen zu Hause",
        "Wassersparen",
        "Ernährungsbedingte Krankheiten",
        "Uebergewicht und Praevention",
        "Essstoerungen erkennen",
        "Ernährung und Sport",
        "Saeuglings- und Kinderernaehrung",
        "Ernährung im Alter",
        "Lebensmittelrecht",
        "Oeko-Labels und Siegel",
        "Fair Trade",
        "Gastronomie und Berufe",
        "Erste Hilfe in der Kueche",
        "Unfallverhuetung",
        "Abitur-Hauswirtschaft",
    ],
    "Ernährungslehre": [
        "Grundlagen der Ernährungswissenschaft",
        "Makronaehrstoffe: Kohlenhydrate",
        "Makronaehrstoffe: Proteine",
        "Makronaehrstoffe: Lipide",
        "Mikronährstoffe: Vitamine (fett-/wasserloeslich)",
        "Mikronährstoffe: Mineralstoffe und Spurenelemente",
        "Wasser: Funktion und Bedarf",
        "Ballaststoffe",
        "Energiebilanz und Grundumsatz",
        "Stoffwechsel: Verdauung",
        "Stoffwechsel: Resorption",
        "Stoffwechsel: Kohlenhydratstoffwechsel",
        "Stoffwechsel: Fettstoffwechsel",
        "Stoffwechsel: Eiweissstoffwechsel",
        "Enzyme in der Verdauung",
        "Ernährungspyramide und DGE-Regeln",
        "Ernährungsformen: Vegetarismus",
        "Ernährungsformen: Veganismus",
        "Ernährungsformen: Low Carb, Keto",
        "Ernährungsformen: Mediterrane Diät",
        "Ernährungsformen: Clean Eating",
        "Ernährung in der Schwangerschaft",
        "Kindernaehrung",
        "Ernährung im Alter",
        "Sporternaehrung",
        "Ernährung bei Diabetes",
        "Ernährung bei Herz-Kreislauf-Erkrankungen",
        "Ernährung bei Adipositas",
        "Lebensmittelallergien (Zoeliakie, Laktose, etc.)",
        "Essstoerungen (Anorexie, Bulimie, Binge Eating)",
        "Lebensmitteltechnologie",
        "Lebensmittelzusatzstoffe (E-Nummern)",
        "Lebensmittelrecht und Kennzeichnung",
        "Lebensmittelhygiene",
        "Lebensmittelsicherheit (HACCP)",
        "Gentechnik in Lebensmitteln",
        "Bio-Lebensmittel",
        "Nachhaltigkeit in der Ernährung",
        "Welternaehrung und Hunger",
        "Lebensmittelverschwendung",
        "Funktionelle Lebensmittel",
        "Probiotika und Praebiotika",
        "Ernährungsberatung als Beruf",
        "Forschungsmethoden Ernährungswissenschaft",
        "Ernährungsprotokolle führen",
        "BMI und Koerperanalyse",
        "Diätetik",
        "Nahrungsergaenzungsmittel",
        "Ernährungsmythen",
        "Abitur-Ernährungslehre",
    ],
}

# Internal subject ID mapping (for quiz_topics.py compatibility)
FACH_TO_SUBJECT_ID: dict[str, str] = {
    "Deutsch": "german",
    "Englisch": "english",
    "Französisch": "french",
    "Latein": "latin",
    "Spanisch": "spanish",
    "Italienisch": "italian",
    "Russisch": "russian",
    "Türkisch": "turkish",
    "Altgriechisch": "ancient_greek",
    "Mathe": "math",
    "Physik": "physics",
    "Chemie": "chemistry",
    "Biologie": "biology",
    "Informatik": "computer_science",
    "Astronomie": "astronomy",
    "Technik": "technology",
    "Geschichte": "history",
    "Geografie": "geography",
    "Politik": "politics",
    "Wirtschaft": "economics",
    "Psychologie": "psychology",
    "Pädagogik": "pedagogy",
    "Sozialwissenschaften": "social_sciences",
    "Philosophie": "philosophy",
    "Recht": "law",
    "Religion (Kath.)": "religion_catholic",
    "Religion (Ev.)": "religion_protestant",
    "Islamunterricht": "islamic_studies",
    "Ethik": "ethics",
    "Werte und Normen": "values_norms",
    "Kunst": "art",
    "Musik": "music",
    "Darstellendes Spiel": "drama",
    "Sport": "sport",
    "Hauswirtschaft": "home_economics",
    "Ernährungslehre": "nutrition",
}

SUBJECT_ID_TO_FACH: dict[str, str] = {v: k for k, v in FACH_TO_SUBJECT_ID.items()}


def get_fächer_by_kategorie() -> dict[str, list[dict]]:
    """Get all subjects grouped by category."""
    result: dict[str, list[dict]] = {k: [] for k in KATEGORIEN}
    for fach, info in ALLE_FAECHER.items():
        kat = info["kategorie"]
        if kat in result:
            result[kat].append({"name": fach, **info})
    return result


def get_fach_info(fach_name: str) -> dict | None:
    """Get info for a single subject by name."""
    return ALLE_FAECHER.get(fach_name)


def get_themen_for_fach(fach_name: str) -> list[str]:
    """Get topics for a subject (from THEMEN_ERWEITERUNG or fallback)."""
    return THEMEN_ERWEITERUNG.get(fach_name, [])


def is_spezial_fach(fach_name: str) -> str | None:
    """Check if a subject has a special mode (e.g., latein_modus)."""
    info = ALLE_FAECHER.get(fach_name, {})
    return info.get("spezial")
